 const CartActionType={
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    DELETE_ITEM_FROM_CART:'DELETE_ITEM_FROM_CART',
    REDUCE_THE_QUANTITY:'REDUCE_THE_QUANTITY'
};

export default CartActionType;